language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: nightly
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update --no-interaction
  - composer --version --no-interaction

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

before_script:
  - composer update --ignore-platform-reqs --prefer-dist $PREFER_LOWEST
  - composer --optimize-autoloader --no-interaction

script:
  - bin/phpunit --configuration . --coverage-clover=build/logs/clover.xml --coverage-html=build/html/coverage

after_script:
  - if [ $(phpenv version-name) == "5.6" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then bin/codacycoverage clover build/logs/clover.xml > /dev/null 2>&1; fi

after_success:
  # Push coverage to github pages branch
  - chmod +x ./update-gh-pages.sh
  - if [ $(phpenv version-name) == "5.6" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then bash ./update-gh-pages.sh; fi
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --tags --quiet https://$GITHUBKEY@github.com/clickalicious/caching-middleware > /dev/null 2>&1

# Blacklist the pushed tag from above to prevent black hole
branches:
  except:
    - /^build-[0-9a-z\-]*/

# Who to notify?
notifications:
  slack:
    secure: aFSqcD9z39hZJgCsJ0QS0ziSLEuqkY5Fuwk7/J9KSIc7+1qqaNACb1IkCxeazcGnpK2JtUvkAsiTyye412Nrym/RP2Yha2YWrlksRjwnm/IyxIo8t4tSI8EnQx+suQauqjiZUjXQm/WIGN4skn42ZAmN9NJfkY+BAqfcxYLAWTO6E9ohbw304Nlr5Khsnlb1Z8QjZgELP7bl4kOyqUjGE5i5nFKe4syH6ApziU+bn+yyESHfdXmsZoozOSwqviDUSiMlLQrzAs0b2kb35D9pk1nLL5HH/bJOf3j7S0CatnXf+BUYuPCu59JrX42NEBEGcdXbuC5PiIwTyN+JUAIHLRNaQ4oKkILBhDvAJes1FEWv/24qjTjgGW09GYoftdgYWzWattVKalvqkxN6q8MURqg2/np9UpyJf1mSkIYXU5fOcpCq3CjL9Tl2LZegOZPB/zl0WzIbmKTR84On9yFirE0SDfv6MS0BH/gzyECBOnmRDrCOA2CWGx0Pbyf4mQWn5cw9rIRxnZOZ5dN8YAG9wNOgRTT26+mitI5H5vGadGAZytfZDPrGi2eyvtAa5UOmvHkHzbHSZhUkmkXXWUM3Z8gLGUuv+EAez0BQ590cmQvTfKvO8W3jTFynR/ZuRQUCRQd11yztexNGPO15kFvzvED2RGhPmHgEtzlNwGm+bw4=
  email:
    recipients:
      - opensource@clickalicious.de
